# Generated by Django 3.2.16 on 2022-12-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('color', models.CharField(choices=[('lightgray', 'lightgray'), ('pink', 'pink'), ('darkred', 'darkred'), ('red', 'red'), ('lightblue', 'lightblue'), ('darkblue', 'darkblue'), ('darkpurple', 'darkpurple'), ('green', 'green'), ('blue', 'blue'), ('lightgreen', 'lightgreen'), ('lightred', 'lightred'), ('gray', 'gray'), ('cadetblue', 'cadetblue'), ('orange', 'orange'), ('purple', 'purple'), ('darkgreen', 'darkgreen'), ('black', 'black'), ('beige', 'beige'), ('white', 'white')], max_length=40)),
                ('experience', models.CharField(choices=[('study', 'study'), ('job', 'job'), ('life_experience', 'life_experience')], max_length=255)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('details', models.TextField(null=True)),
            ],
        ),
    ]
