# Generated by Django 3.2.16 on 2022-12-28 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('baner', models.ImageField(blank=True, null=True, upload_to='apps/static/assets/img/temp/')),
                ('description', models.TextField(blank=True, null=True)),
                ('video', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField(blank=True, null=True)),
                ('footer', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='apps/static/assets/img/temp/')),
                ('code', models.TextField(blank=True, null=True)),
                ('video', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='apps/static/assets/img/temp/')),
                ('description', models.TextField(blank=True, null=True)),
                ('blog', models.ManyToManyField(blank=True, to='blog.Blog')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='message',
            field=models.ManyToManyField(blank=True, to='blog.Message'),
        ),
        migrations.AddField(
            model_name='blog',
            name='posts',
            field=models.ManyToManyField(blank=True, to='blog.Posts'),
        ),
    ]
