# Generated by Django 3.2.16 on 2022-12-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('To Do', 'To Do'), ('Working', 'Working'), ('Done', 'Done')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('baner', models.ImageField(upload_to='apps/static/assets/img/temp/')),
                ('TYPE', models.CharField(choices=[('0', 'public'), ('1', 'private')], max_length=10)),
                ('description2', models.TextField()),
                ('progress', models.IntegerField(blank=True, default=0, null=True)),
                ('required_value', models.FloatField(blank=True, null=True)),
                ('amount_donated', models.FloatField(blank=True, null=True)),
                ('biticon_request', models.CharField(blank=True, max_length=500, null=True)),
                ('task', models.ManyToManyField(to='project.Task')),
            ],
        ),
    ]
